services:
  auth-service:
    build:
      context: ./services/auth
    container_name: tgi_auth
    environment:
      - VALID_TOKEN=${VALID_TOKEN:?VALID_TOKEN is required}
    networks:
      - tgi_net
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256M
    mem_reservation: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - "3000"
    logging:  # Add detailed logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
      - "traefik.http.routers.auth.rule=PathPrefix(`/validate`)"
      - "traefik.http.middlewares.auth-headers.headers.customResponseHeaders.X-Frame-Options=DENY"
    restart: unless-stopped

  proxy:
    image: traefik:v3.2.1
    container_name: tgi_proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${SERVICE_PORT:?SERVICE_PORT is required}"
      - "--entrypoints.traefik.address=:8080"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--log.level=DEBUG"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik/dynamic:ro
    networks:
      - tgi_net
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      - VALID_TOKEN=${VALID_TOKEN:?VALID_TOKEN is required}
    mem_limit: 512M
    mem_reservation: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://auth-service:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:  # Add detailed logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

networks:
  tgi_net:
    external: true
    name: tgi_network
